### ISSUE TITLE
Gitbot not working

### ISSUE THREAD

**Issue by shawnw** [pennmush/notifier#1]
Gitbot hasn't been making announcements on MUSH for a few days. @tkrajcar is that yours?

**Comment by tkrajcar** [comment]
Yeah, it's because my Heroku account ran out of free hours due to some other apps using them all up :) I converted a different app to paid, so it shouldn't be an issue in the future. The quota resets tomorrow, so it should start working again then.

**Comment by shawnw** [comment]
Yup, working again.
